### ISSUE TITLE
bump_changelog() fails on a previous hotfix build

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/rhcephpkg#128]
`bump_changelog()` cannot handle the `28.2.bz1445891` Release value here:
```
$ rhcephpkg patch
gbp:info: Generating patches from git (ceph-2.2-ubuntu-test-bz1464099..patch-queue/ceph-2.2-ubuntu-test-bz1464099)
On branch ceph-2.2-ubuntu-test-bz1464099
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
 
        modified:   debian/patches/series
 
Untracked files:
  (use "git add <file>..." to include in what will be committed)
 
        debian/patches/0145-rgw-cls-ceph-timespan-tag_timeout-wrong-units.patch
 
no changes added to commit (use "git add" and/or "git commit -a")
Traceback (most recent call last):
  File "/usr/bin/rhcephpkg", line 6, in <module>
    main.RHCephPkg()
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/main.py", line 35, in __init__
    self.main(argv)
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/main.py", line 54, in main
    parser.dispatch()
  File "/usr/lib/python2.7/dist-packages/tambo/dispatcher.py", line 21, in dispatch
    return instance.main()
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/patch.py", line 26, in main
    self._run()
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/patch.py", line 87, in _run
    util.bump_changelog(changelog)
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/util.py", line 99, in bump_changelog
    version = get_deb_version()
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/util.py", line 134, in get_deb_version
    return DebVersion(vstr)
  File "/usr/lib/python2.7/dist-packages/rhcephpkg/util.py", line 147, in __init__
    self.releaseint = int(release.split('redhat', 1)[0])
ValueError: invalid literal for int() with base 10: '28.2.bz1445891'
```

**Comment by ktdreyer** [comment]
Fixed in https://github.com/red-hat-storage/rhcephpkg/pull/130
